spring.application.name=KANAN-TUX-BACKEND

# ===============================
# SERVIDOR
# ===============================
server.port=8080

# ===============================
# POSTGRESQL
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/kanan_tux_db
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA
# ===============================
# Clave secreta para firmar los Tokens JWT
jwt.secret=c2VjcmV0LWtleS1kZWZpbmlkYS1wYXJhLWthbmFuLXR1eC1iYWNrZW5kLTIwMjY=
# Hibernate sabe que usamos PostgreSQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# NO crear tablas
# NO modificar tablas
spring.jpa.hibernate.ddl-auto=none

# Mostrar SQL
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# SECURITY (Temporal)
# ===============================

spring.security.user.name=admin
spring.security.user.password=admin