spring.application.name=KANAN-TUX-BACKEND

# ===============================
# SERVIDOR
# ===============================
server.port=8080

# ===============================
# POSTGRESQL
# ===============================
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/kanan_tux_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:root}
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA
# ===============================
jwt.secret=${JWT_SECRET:c2VjcmV0LWtleS1kZWZpbmlkYS1wYXJhLWthbmFuLXR1eC1iYWNrZW5kLTIwMjY=}
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

# ===============================
# SECURITY (Temporal)
# ===============================
spring.security.user.name=admin
spring.security.user.password=admin

# ===============================
# MAIL (Vía Brevo HTTP API)
# ===============================
brevo.api.key=${BREVO_API_KEY}